name: Docker CI

on:
  push:
    branches: [ "main", "master" ] # Сработает, когда отправишь код в эти ветки

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-test-app .

      - name: Run Tests in Docker
        run: docker run my-test-app